"use client";
import { useMemo, useState } from "react";
import { aud, invoiceCategories, invoiceContexts, invoiceUnits } from "@/lib/invoices";

type Client={id:string;name:string;email:string|null;phone:string|null};
type Rate={id:string;client_id:string|null;service_name:string;category:string;work_context:string;unit:string;rate_cents:number};
type Line={description:string;category:string;work_context:string;quantity:number;unit:string;unit_price_cents:number};
const blank=():Line=>({description:"",category:"Photography",work_context:"On location",quantity:1,unit:"hour",unit_price_cents:0});
export function InvoiceComposer({clients,rates,issueDate,dueDate,dueDays=14,gstRate=0,notes=""}:{clients:Client[];rates:Rate[];issueDate?:string;dueDate?:string;dueDays?:number;gstRate?:number;notes?:string}){
 const [clientId,setClientId]=useState("");const [name,setName]=useState("");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [address,setAddress]=useState("");const [project,setProject]=useState("");const [invoiceNotes,setInvoiceNotes]=useState(notes);const [lines,setLines]=useState<Line[]>([blank()]);const [gst,setGst]=useState(gstRate);
 // Dates are captured once for this newly opened draft form.
 const [dates]=useState(()=>{const now=Date.now();return {issue:new Date(now).toISOString().slice(0,10),due:new Date(now+dueDays*86400000).toISOString().slice(0,10)}});const subtotal=useMemo(()=>lines.reduce((s,l)=>s+Math.round(l.quantity*l.unit_price_cents),0),[lines]);const gstCents=Math.round(subtotal*gst/100);
 function chooseClient(value:string){setClientId(value);const c=clients.find(x=>x.id===value);if(c){setName(c.name);setEmail(c.email||"");setPhone(c.phone||"");}}
 function patchLine(i:number,p:Partial<Line>){setLines(current=>current.map((line,n)=>n===i?{...line,...p}:line));}
 function addRate(rate:Rate){setLines(current=>[...current.filter(l=>l.description),{description:rate.service_name,category:rate.category,work_context:rate.work_context,quantity:1,unit:rate.unit,unit_price_cents:rate.rate_cents}]);}
 const payload={client_id:clientId||null,client_name:name,client_email:email,client_phone:phone,client_address:address,project_title:project,issue_date:issueDate||dates.issue,due_date:dueDate||dates.due,gst_rate:gst,notes:invoiceNotes,terms:"Payment is due by the date shown.",items:lines};
 return <div className="invoice-composer">
  <div className="invoice-form-grid"><label>Saved client<select value={clientId} onChange={e=>chooseClient(e.target.value)}><option value="">One-off client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Client name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>Project / job<input value={project} onChange={e=>setProject(e.target.value)} placeholder="Campaign, shoot, edit…"/></label><label>Client billing address<input value={address} onChange={e=>setAddress(e.target.value)}/></label><label>Issue date<input value={issueDate||dates.issue} readOnly/></label><label>Due date<input value={dueDate||dates.due} readOnly/></label></div>
  <div className="invoice-rate-picks"><span>Quick add:</span>{rates.filter(r=>!r.client_id||r.client_id===clientId).map(r=><button type="button" key={r.id} onClick={()=>addRate(r)}>{r.service_name} · {aud(r.rate_cents)}/{r.unit}</button>)}</div>
  <div className="invoice-lines"><div className="invoice-line invoice-line-head"><span>Service</span><span>Type</span><span>Setting</span><span>Qty</span><span>Unit</span><span>Rate</span><span></span></div>{lines.map((line,i)=><div className="invoice-line" key={i}><input aria-label="Service" value={line.description} onChange={e=>patchLine(i,{description:e.target.value})}/><select aria-label="Type" value={line.category} onChange={e=>patchLine(i,{category:e.target.value})}>{invoiceCategories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Setting" value={line.work_context} onChange={e=>patchLine(i,{work_context:e.target.value})}>{invoiceContexts.map(x=><option key={x}>{x}</option>)}</select><input aria-label="Quantity" type="number" min="0.25" step="0.25" value={line.quantity} onChange={e=>patchLine(i,{quantity:Number(e.target.value)})}/><select aria-label="Unit" value={line.unit} onChange={e=>patchLine(i,{unit:e.target.value})}>{invoiceUnits.map(x=><option key={x}>{x}</option>)}</select><input aria-label="Rate" type="number" min="0" step="0.01" value={line.unit_price_cents/100} onChange={e=>patchLine(i,{unit_price_cents:Math.round(Number(e.target.value)*100)})}/><button type="button" aria-label="Remove line" onClick={()=>setLines(x=>x.length===1?[blank()]:x.filter((_,n)=>n!==i))}>×</button></div>)}</div>
  <button className="invoice-secondary" type="button" onClick={()=>setLines(x=>[...x,blank()])}>+ Add custom line</button>
  <div className="invoice-bottom"><div><label>GST rate % <input type="number" min="0" max="100" step="0.1" value={gst} onChange={e=>setGst(Number(e.target.value))}/></label><p>Use 0% unless you are registered for GST.</p><label>Invoice note<textarea value={invoiceNotes} onChange={e=>setInvoiceNotes(e.target.value)} placeholder="Thank you, usage details, or payment note"/></label></div><dl><div><dt>Subtotal</dt><dd>{aud(subtotal)}</dd></div><div><dt>GST</dt><dd>{aud(gstCents)}</dd></div><div><dt>Total</dt><dd>{aud(subtotal+gstCents)}</dd></div></dl></div>
  <input type="hidden" name="payload" value={JSON.stringify(payload)}/><button className="invoice-primary" type="submit" disabled={!name||!email||!lines.some(l=>l.description)}>Create draft invoice</button>
 </div>
}
